import { jsx as _jsx } from "react/jsx-runtime";
import React, { createContext, useContext, useState, useEffect } from 'react';
const LanguageContext = createContext(undefined);
const translations = {
    fr: {
        // Navigation
        'nav.buy': 'Acheter',
        'nav.rent': 'Louer',
        'nav.agencies': 'Agences',
        'nav.advertise': 'Annoncer avec nous',
        'nav.addListing': 'Ajouter une annonce',
        'nav.login': 'Connexion',
        'nav.register': 'Inscription',
        'nav.dashboard': 'Tableau de bord',
        'nav.logout': 'Déconnexion',
        'nav.myListings': 'Mes annonces',
        'nav.advertising': 'Publicité',
        'nav.admin': 'Administration',
        // Hero
        'hero.title': 'Trouvez votre',
        'hero.titleHighlight': 'Propriété Idéale',
        'hero.subtitle': 'Découvrez des propriétés exceptionnelles à travers le Maroc. Que vous achetiez, louiez ou vendiez – nous sommes là pour vous aider.',
        'hero.forSale': 'À Vendre',
        'hero.forRent': 'À Louer',
        'hero.selectCity': 'Sélectionner une ville',
        'hero.propertyType': 'Type de bien',
        'hero.maxPrice': 'Prix max',
        'hero.search': 'Rechercher',
        // Property Types
        'property.apartment': 'Appartement',
        'property.house': 'Maison',
        'property.villa': 'Villa',
        'property.commercial': 'Commercial',
        'property.land': 'Terrain',
        // Property Card
        'property.bedrooms': 'Chambres',
        'property.bathrooms': 'Salles de bain',
        'property.area': 'm²',
        'property.forSale': 'À Vendre',
        'property.forRent': 'À Louer',
        'property.perMonth': '/mois',
        // Featured & Latest
        'featured.title': 'Propriétés en Vedette',
        'featured.subtitle': 'Sélection premium de nos meilleures annonces',
        'latest.title': 'Dernières Annonces',
        'latest.subtitle': 'Propriétés récemment ajoutées',
        'viewAll': 'Voir tout',
        // CTA Section
        'cta.title': 'Prêt à publier votre propriété ?',
        'cta.subtitle': 'Rejoignez des milliers de propriétaires et d\'agences qui font confiance à TopAffaireImmo',
        'cta.button': 'Publier une annonce',
        // Auth
        'auth.login': 'Connexion',
        'auth.register': 'Inscription',
        'auth.email': 'Email',
        'auth.password': 'Mot de passe',
        'auth.confirmPassword': 'Confirmer le mot de passe',
        'auth.fullName': 'Nom complet',
        'auth.phone': 'Téléphone',
        'auth.loginButton': 'Se connecter',
        'auth.registerButton': 'S\'inscrire',
        'auth.noAccount': 'Pas de compte ?',
        'auth.haveAccount': 'Déjà un compte ?',
        'auth.forgotPassword': 'Mot de passe oublié ?',
        'auth.orContinue': 'Ou continuer avec',
        // Dashboard
        'dashboard.title': 'Tableau de bord',
        'dashboard.myListings': 'Mes annonces',
        'dashboard.addNew': 'Ajouter une annonce',
        'dashboard.status': 'Statut',
        'dashboard.pending': 'En attente',
        'dashboard.approved': 'Approuvée',
        'dashboard.rejected': 'Refusée',
        'dashboard.inactive': 'Inactive',
        'dashboard.edit': 'Modifier',
        'dashboard.delete': 'Supprimer',
        'dashboard.noListings': 'Aucune annonce pour le moment',
        'dashboard.createFirst': 'Créez votre première annonce',
        // Add Listing
        'addListing.title': 'Ajouter une propriété',
        'addListing.subtitle': 'Remplissez les détails pour publier votre annonce',
        'addListing.transactionType': 'Type de transaction',
        'addListing.propertyType': 'Type de bien',
        'addListing.city': 'Ville',
        'addListing.neighborhood': 'Quartier',
        'addListing.selectNeighborhood': 'Sélectionner un quartier',
        'addListing.customNeighborhood': 'Autre quartier (si non listé)',
        'addListing.address': 'Adresse',
        'addListing.price': 'Prix (MAD)',
        'addListing.area': 'Surface (m²)',
        'addListing.bedrooms': 'Chambres',
        'addListing.bathrooms': 'Salles de bain',
        'addListing.title_fr': 'Titre (Français)',
        'addListing.title_ar': 'Titre (Arabe)',
        'addListing.description_fr': 'Description (Français)',
        'addListing.description_ar': 'Description (Arabe)',
        'addListing.images': 'Photos',
        'addListing.uploadImages': 'Télécharger des photos',
        'addListing.phone': 'Téléphone de contact',
        'addListing.submit': 'Publier l\'annonce',
        'addListing.success': 'Annonce soumise !',
        'addListing.successMessage': 'Votre annonce sera examinée et publiée sous 24h.',
        'addListing.loginRequired': 'Veuillez vous connecter pour publier une annonce',
        // Search Results
        'search.results': 'Résultats de recherche',
        'search.noResults': 'Aucun résultat trouvé',
        'search.filters': 'Filtres',
        // Footer
        'footer.about': 'À propos',
        'footer.contact': 'Contact',
        'footer.privacy': 'Confidentialité',
        'footer.terms': 'Conditions',
        'footer.rights': 'Tous droits réservés',
        // Common
        'common.loading': 'Chargement...',
        'common.error': 'Erreur',
        'common.success': 'Succès',
        'common.cancel': 'Annuler',
        'common.save': 'Enregistrer',
        'common.confirm': 'Confirmer',
        'common.back': 'Retour',
        // Advertising
        'advertising.title': 'Publicité',
        'advertising.loginRequired': 'Connectez-vous pour voir les options publicitaires',
        'advertising.loginMessage': 'Veuillez vous connecter ou créer un compte annonceur pour voir les options publicitaires.',
        'advertising.dashboard': 'Tableau de bord publicitaire',
        'advertising.myAds': 'Mes publicités',
        'advertising.newRequest': 'Nouvelle demande',
        'advertising.availableSlots': 'Emplacements disponibles',
        'advertising.slot': 'Emplacement',
        'advertising.page': 'Page',
        'advertising.position': 'Position',
        'advertising.size': 'Taille',
        'advertising.pricing': 'Tarification',
        'advertising.duration': 'Durée',
        'advertising.days': 'jours',
        'advertising.price': 'Prix',
        'advertising.companyName': 'Nom de l\'entreprise',
        'advertising.contactEmail': 'Email de contact',
        'advertising.contactPhone': 'Téléphone de contact',
        'advertising.selectSlot': 'Sélectionner un emplacement',
        'advertising.selectDuration': 'Sélectionner la durée',
        'advertising.bannerImage': 'Image de la bannière',
        'advertising.uploadBanner': 'Télécharger la bannière',
        'advertising.targetUrl': 'URL cible',
        'advertising.paymentProof': 'Preuve de paiement',
        'advertising.uploadPayment': 'Télécharger la preuve de paiement',
        'advertising.submitRequest': 'Soumettre la demande',
        'advertising.requestSubmitted': 'Demande soumise!',
        'advertising.requestMessage': 'Votre demande publicitaire a été soumise. Notre équipe l\'examinera sous 24-48h.',
        'advertising.status': 'Statut',
        'advertising.pending': 'En attente',
        'advertising.approved': 'Approuvée',
        'advertising.active': 'Active',
        'advertising.rejected': 'Refusée',
        'advertising.expired': 'Expirée',
        'advertising.startDate': 'Date de début',
        'advertising.endDate': 'Date de fin',
        'advertising.noAds': 'Aucune publicité pour le moment',
        'advertising.createFirst': 'Créez votre première campagne publicitaire',
        'advertising.bankTransfer': 'Virement bancaire',
        'advertising.bankDetails': 'Coordonnées bancaires',
        'advertising.7days': '7 jours - 800 MAD',
        'advertising.15days': '15 jours - 1 400 MAD',
        'advertising.30days': '30 jours - 2 500 MAD',
        // Admin
        'admin.title': 'Administration',
        'admin.bannerRequests': 'Demandes de bannières',
        'admin.approve': 'Approuver',
        'admin.reject': 'Rejeter',
        'admin.viewPayment': 'Voir le paiement',
        'admin.viewBanner': 'Voir la bannière',
        'admin.notes': 'Notes',
    },
    ar: {
        // Navigation
        'nav.buy': 'شراء',
        'nav.rent': 'إيجار',
        'nav.agencies': 'الوكالات',
        'nav.advertise': 'أعلن معنا',
        'nav.addListing': 'إضافة إعلان',
        'nav.login': 'تسجيل الدخول',
        'nav.register': 'إنشاء حساب',
        'nav.dashboard': 'لوحة التحكم',
        'nav.logout': 'تسجيل الخروج',
        'nav.myListings': 'إعلاناتي',
        'nav.advertising': 'الإعلانات',
        'nav.admin': 'الإدارة',
        // Hero
        'hero.title': 'اعثر على',
        'hero.titleHighlight': 'عقارك المثالي',
        'hero.subtitle': 'اكتشف عقارات استثنائية في جميع أنحاء المغرب. سواء كنت تشتري أو تستأجر أو تبيع – نحن هنا لمساعدتك.',
        'hero.forSale': 'للبيع',
        'hero.forRent': 'للإيجار',
        'hero.selectCity': 'اختر مدينة',
        'hero.propertyType': 'نوع العقار',
        'hero.maxPrice': 'السعر الأقصى',
        'hero.search': 'بحث',
        // Property Types
        'property.apartment': 'شقة',
        'property.house': 'منزل',
        'property.villa': 'فيلا',
        'property.commercial': 'تجاري',
        'property.land': 'أرض',
        // Property Card
        'property.bedrooms': 'غرف النوم',
        'property.bathrooms': 'الحمامات',
        'property.area': 'م²',
        'property.forSale': 'للبيع',
        'property.forRent': 'للإيجار',
        'property.perMonth': '/شهر',
        // Featured & Latest
        'featured.title': 'عقارات مميزة',
        'featured.subtitle': 'مجموعة مختارة من أفضل إعلاناتنا',
        'latest.title': 'أحدث الإعلانات',
        'latest.subtitle': 'عقارات أضيفت مؤخراً',
        'viewAll': 'عرض الكل',
        // CTA Section
        'cta.title': 'هل أنت مستعد لنشر عقارك؟',
        'cta.subtitle': 'انضم إلى آلاف المالكين والوكالات الذين يثقون في TopAffaireImmo',
        'cta.button': 'نشر إعلان',
        // Auth
        'auth.login': 'تسجيل الدخول',
        'auth.register': 'إنشاء حساب',
        'auth.email': 'البريد الإلكتروني',
        'auth.password': 'كلمة المرور',
        'auth.confirmPassword': 'تأكيد كلمة المرور',
        'auth.fullName': 'الاسم الكامل',
        'auth.phone': 'الهاتف',
        'auth.loginButton': 'دخول',
        'auth.registerButton': 'تسجيل',
        'auth.noAccount': 'ليس لديك حساب؟',
        'auth.haveAccount': 'لديك حساب بالفعل؟',
        'auth.forgotPassword': 'نسيت كلمة المرور؟',
        'auth.orContinue': 'أو المتابعة مع',
        // Dashboard
        'dashboard.title': 'لوحة التحكم',
        'dashboard.myListings': 'إعلاناتي',
        'dashboard.addNew': 'إضافة إعلان',
        'dashboard.status': 'الحالة',
        'dashboard.pending': 'قيد الانتظار',
        'dashboard.approved': 'معتمد',
        'dashboard.rejected': 'مرفوض',
        'dashboard.inactive': 'غير نشط',
        'dashboard.edit': 'تعديل',
        'dashboard.delete': 'حذف',
        'dashboard.noListings': 'لا توجد إعلانات حتى الآن',
        'dashboard.createFirst': 'أنشئ إعلانك الأول',
        // Add Listing
        'addListing.title': 'إضافة عقار',
        'addListing.subtitle': 'املأ التفاصيل لنشر إعلانك',
        'addListing.transactionType': 'نوع المعاملة',
        'addListing.propertyType': 'نوع العقار',
        'addListing.city': 'المدينة',
        'addListing.neighborhood': 'الحي',
        'addListing.selectNeighborhood': 'اختر الحي',
        'addListing.customNeighborhood': 'حي آخر (إذا لم يكن مدرجاً)',
        'addListing.address': 'العنوان',
        'addListing.price': 'السعر (درهم)',
        'addListing.area': 'المساحة (م²)',
        'addListing.bedrooms': 'غرف النوم',
        'addListing.bathrooms': 'الحمامات',
        'addListing.title_fr': 'العنوان (فرنسي)',
        'addListing.title_ar': 'العنوان (عربي)',
        'addListing.description_fr': 'الوصف (فرنسي)',
        'addListing.description_ar': 'الوصف (عربي)',
        'addListing.images': 'الصور',
        'addListing.uploadImages': 'تحميل الصور',
        'addListing.phone': 'هاتف التواصل',
        'addListing.submit': 'نشر الإعلان',
        'addListing.success': 'تم إرسال الإعلان!',
        'addListing.successMessage': 'سيتم مراجعة إعلانك ونشره خلال 24 ساعة.',
        'addListing.loginRequired': 'يرجى تسجيل الدخول لنشر إعلان',
        // Search Results
        'search.results': 'نتائج البحث',
        'search.noResults': 'لم يتم العثور على نتائج',
        'search.filters': 'الفلاتر',
        // Footer
        'footer.about': 'حول',
        'footer.contact': 'اتصل بنا',
        'footer.privacy': 'الخصوصية',
        'footer.terms': 'الشروط',
        'footer.rights': 'جميع الحقوق محفوظة',
        // Common
        'common.loading': 'جاري التحميل...',
        'common.error': 'خطأ',
        'common.success': 'نجاح',
        'common.cancel': 'إلغاء',
        'common.save': 'حفظ',
        'common.confirm': 'تأكيد',
        'common.back': 'رجوع',
        // Advertising
        'advertising.title': 'الإعلانات',
        'advertising.loginRequired': 'سجل الدخول لعرض خيارات الإعلان',
        'advertising.loginMessage': 'يرجى تسجيل الدخول أو إنشاء حساب معلن لعرض خيارات الإعلان.',
        'advertising.dashboard': 'لوحة تحكم الإعلانات',
        'advertising.myAds': 'إعلاناتي',
        'advertising.newRequest': 'طلب جديد',
        'advertising.availableSlots': 'المواقع المتاحة',
        'advertising.slot': 'الموقع',
        'advertising.page': 'الصفحة',
        'advertising.position': 'الموضع',
        'advertising.size': 'الحجم',
        'advertising.pricing': 'التسعير',
        'advertising.duration': 'المدة',
        'advertising.days': 'أيام',
        'advertising.price': 'السعر',
        'advertising.companyName': 'اسم الشركة',
        'advertising.contactEmail': 'البريد الإلكتروني',
        'advertising.contactPhone': 'رقم الهاتف',
        'advertising.selectSlot': 'اختر موقعاً',
        'advertising.selectDuration': 'اختر المدة',
        'advertising.bannerImage': 'صورة البانر',
        'advertising.uploadBanner': 'رفع البانر',
        'advertising.targetUrl': 'رابط الوجهة',
        'advertising.paymentProof': 'إثبات الدفع',
        'advertising.uploadPayment': 'رفع إثبات الدفع',
        'advertising.submitRequest': 'إرسال الطلب',
        'advertising.requestSubmitted': 'تم إرسال الطلب!',
        'advertising.requestMessage': 'تم إرسال طلبك الإعلاني. سيقوم فريقنا بمراجعته خلال 24-48 ساعة.',
        'advertising.status': 'الحالة',
        'advertising.pending': 'قيد الانتظار',
        'advertising.approved': 'موافق عليه',
        'advertising.active': 'نشط',
        'advertising.rejected': 'مرفوض',
        'advertising.expired': 'منتهي',
        'advertising.startDate': 'تاريخ البدء',
        'advertising.endDate': 'تاريخ الانتهاء',
        'advertising.noAds': 'لا توجد إعلانات حتى الآن',
        'advertising.createFirst': 'أنشئ حملتك الإعلانية الأولى',
        'advertising.bankTransfer': 'تحويل بنكي',
        'advertising.bankDetails': 'تفاصيل الحساب البنكي',
        'advertising.7days': '7 أيام - 800 درهم',
        'advertising.15days': '15 يوم - 1,400 درهم',
        'advertising.30days': '30 يوم - 2,500 درهم',
        // Admin
        'admin.title': 'الإدارة',
        'admin.bannerRequests': 'طلبات البانر',
        'admin.approve': 'موافقة',
        'admin.reject': 'رفض',
        'admin.viewPayment': 'عرض الدفع',
        'admin.viewBanner': 'عرض البانر',
        'admin.notes': 'ملاحظات',
    },
};
export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'fr';
    });
    const setLanguage = (lang) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };
    const t = (key) => {
        return translations[language][key] || key;
    };
    const isRTL = language === 'ar';
    useEffect(() => {
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language, isRTL]);
    return (_jsx(LanguageContext.Provider, { value: { language, setLanguage, t, isRTL }, children: children }));
}
export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
