import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { useLanguage } from "@/contexts/LanguageContext";
import { Button } from "@/components/ui/button";
import { Plus, Building2, ArrowRight } from "lucide-react";
export default function CTASection() {
    const { t, isRTL } = useLanguage();
    return (_jsx("section", { className: `py-16 md:py-24 bg-background noise-texture ${isRTL ? 'rtl' : 'ltr'}`, children: _jsx("div", { className: "container", children: _jsxs("div", { className: "grid md:grid-cols-2 gap-6 md:gap-8", children: [_jsxs("div", { className: "relative overflow-hidden rounded-2xl bg-primary p-8 md:p-10 text-white", children: [_jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "inline-flex items-center justify-center w-14 h-14 rounded-xl bg-white/20 mb-6", children: _jsx(Plus, { className: "h-7 w-7" }) }), _jsx("h3", { className: "font-display text-2xl md:text-3xl font-semibold mb-3", children: isRTL ? 'أضف عقارك' : 'Publiez votre bien' }), _jsx("p", { className: "text-white/80 mb-6 max-w-sm", children: isRTL
                                            ? 'تواصل مع آلاف المشترين والمستأجرين المحتملين. انشر إعلانك مجاناً واحصل على مزيد من الرؤية.'
                                            : 'Atteignez des milliers d\'acheteurs et locataires potentiels. Publiez votre annonce gratuitement.' }), _jsx(Button, { asChild: true, size: "lg", variant: "secondary", className: "bg-white text-primary hover:bg-white/90", children: _jsxs(Link, { to: "/add-listing", children: [t('nav.addListing'), _jsx(ArrowRight, { className: `h-4 w-4 ${isRTL ? 'mr-2 rotate-180' : 'ml-2'}` })] }) })] }), _jsx("div", { className: `absolute top-0 ${isRTL ? 'left-0 -translate-x-1/2' : 'right-0 translate-x-1/2'} w-64 h-64 bg-white/10 rounded-full -translate-y-1/2` }), _jsx("div", { className: `absolute bottom-0 ${isRTL ? 'right-0 translate-x-1/2' : 'left-0 -translate-x-1/2'} w-40 h-40 bg-white/5 rounded-full translate-y-1/2` })] }), _jsxs("div", { className: "relative overflow-hidden rounded-2xl bg-secondary p-8 md:p-10 text-white", children: [_jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "inline-flex items-center justify-center w-14 h-14 rounded-xl bg-white/20 mb-6", children: _jsx(Building2, { className: "h-7 w-7" }) }), _jsx("h3", { className: "font-display text-2xl md:text-3xl font-semibold mb-3", children: isRTL ? 'للوكالات العقارية' : 'Pour les agences immobilières' }), _jsx("p", { className: "text-white/80 mb-6 max-w-sm", children: isRTL
                                            ? 'انضم إلى شبكتنا من الوكالات الموثوقة. احصل على ميزات متميزة وتحليلات وأدوات لتنمية عملك.'
                                            : 'Rejoignez notre réseau d\'agences de confiance. Obtenez des fonctionnalités premium et des outils pour développer votre activité.' }), _jsx(Button, { asChild: true, size: "lg", variant: "secondary", className: "bg-white text-secondary hover:bg-white/90", children: _jsxs(Link, { to: "/register", children: [isRTL ? 'سجل الآن' : 'Inscrivez-vous', _jsx(ArrowRight, { className: `h-4 w-4 ${isRTL ? 'mr-2 rotate-180' : 'ml-2'}` })] }) })] }), _jsx("div", { className: `absolute top-0 ${isRTL ? 'left-0 -translate-x-1/2' : 'right-0 translate-x-1/2'} w-64 h-64 bg-white/10 rounded-full -translate-y-1/2` }), _jsx("div", { className: `absolute bottom-0 ${isRTL ? 'right-0 translate-x-1/2' : 'left-0 -translate-x-1/2'} w-40 h-40 bg-white/5 rounded-full translate-y-1/2` })] })] }) }) }));
}
