/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string }>;
};

// Service Worker version - increment to force update
const SW_VERSION = '1.0.2';

// Take control of all clients immediately
clientsClaim();

// Precache all assets generated by Vite PWA plugin
precacheAndRoute(self.__WB_MANIFEST);

// FIX: Bypass /admin routes to prevent offline fallback hijacking
// Admin routes must always reach the network to handle auth properly
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);
  
  // If request is for /admin or /admin/*, bypass service worker entirely
  if (url.pathname === '/admin' || url.pathname.startsWith('/admin/')) {
    event.respondWith(fetch(event.request));
    return;
  }
});

// Runtime caching strategies (same as vite.config.ts)
// Cache images (CacheFirst)
registerRoute(
  ({ url }) => url.pathname.match(/\.(?:png|jpg|jpeg|svg|gif|webp|avif)$/i),
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase Storage images (CacheFirst)
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/storage/v1/object/public/'),
  new CacheFirst({
    cacheName: 'supabase-images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase API calls (NetworkFirst) - EXCLUDE auth endpoints
registerRoute(
  ({ url, request }) => {
    // Only cache GET requests
    if (request.method !== 'GET') return false;
    
    // Don't cache auth endpoints
    if (url.pathname.includes('/auth/')) return false;
    
    // Don't cache if has auth header
    const hasAuthHeader = request.headers.has('Authorization') || 
                         request.headers.has('apikey');
    if (hasAuthHeader) return false;
    
    // Cache Supabase REST API calls
    return url.hostname.includes('supabase.co') && 
           url.pathname.includes('/rest/');
  },
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Google Fonts (CacheFirst)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || 
               url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// ============================================================================
// PUSH NOTIFICATION HANDLERS
// ============================================================================

/**
 * Handle push notification received event
 * Display a notification to the user
 */
self.addEventListener('push', (event: PushEvent) => {
  console.log('[Service Worker] Push notification received:', event);

  if (!event.data) {
    console.log('[Service Worker] Push event has no data');
    return;
  }

  try {
    const data = event.data.json();
    const title = data.title || 'TopAffaireImmo';
    const options: NotificationOptions = {
      body: data.body || '',
      icon: data.icon || '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      tag: data.tag || 'default',
      requireInteraction: data.requireInteraction || false,
      data: data.data || {},
      // Action buttons (optional) - Typed as any to avoid NotificationOptions type issues
    } as NotificationOptions & { actions?: Array<{ action: string; title: string }> };

    // Add actions if provided
    if (data.actions) {
      (options as any).actions = data.actions;
    }

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (error) {
    console.error('[Service Worker] Error handling push event:', error);
    
    // Fallback: show basic notification
    event.waitUntil(
      self.registration.showNotification('TopAffaireImmo', {
        body: 'Vous avez une nouvelle notification',
        icon: '/icons/icon-192.png',
      })
    );
  }
});

/**
 * Handle notification click event
 * Open the app or navigate to specific URL
 */
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[Service Worker] Notification clicked:', event);

  event.notification.close();

  // Get the URL to open from notification data
  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    // Check if there's already a window open
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url === new URL(urlToOpen, self.location.origin).href && 'focus' in client) {
          return client.focus();
        }
      }
      
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

/**
 * Handle push subscription change
 * This is called when a push subscription expires or is replaced
 */
self.addEventListener('pushsubscriptionchange', (event: Event) => {
  console.log('[Service Worker] Push subscription changed:', event);
  
  // You can implement automatic re-subscription here if needed
  // For now, we'll just log it
});

// Skip waiting and claim clients immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

console.log('[Service Worker] Loaded with push notification support');
