/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string }>;
};

// Service Worker version - increment to force update
const SW_VERSION = '1.1.0'; // Updated: Smart offline fallback logic

// Take control of all clients immediately
clientsClaim();

// Precache all assets generated by Vite PWA plugin
precacheAndRoute(self.__WB_MANIFEST);

// Explicitly precache the offline page
// This ensures it's always available when truly offline
self.addEventListener('install', (event: ExtendableEvent) => {
  event.waitUntil(
    caches.open('workbox-precache-v2-' + self.location.origin).then(cache => {
      return cache.addAll([
        '/offline.html',
        '/index.html',
      ]).catch(err => {
        console.warn('[SW] Failed to precache offline fallback pages:', err);
      });
    })
  );
});

// ============================================================================
// SMART OFFLINE FALLBACK HANDLER
// ============================================================================

/**
 * Critical authenticated routes that should NEVER show the offline page
 * Instead, they should return cached app shell or let the app handle the error
 */
const CRITICAL_ROUTES = [
  '/add-listing',
  '/edit-listing',
  '/dashboard',
  '/admin',
  '/profile',
  '/messages',
];

/**
 * Check if the request is for a critical route
 */
function isCriticalRoute(pathname: string): boolean {
  return CRITICAL_ROUTES.some(route => 
    pathname === route || pathname.startsWith(route + '/')
  );
}

/**
 * Check if the request is a navigation request (user navigating to a page)
 */
function isNavigationRequest(request: Request): boolean {
  return request.mode === 'navigate' || request.destination === 'document';
}

/**
 * Check if the request is an API request
 */
function isApiRequest(url: URL): boolean {
  // Supabase API requests
  if (url.hostname.includes('supabase.co')) return true;
  
  // Any /api/* paths
  if (url.pathname.startsWith('/api/')) return true;
  
  return false;
}

/**
 * Smart fetch handler that implements safe offline fallback
 * 
 * Rules:
 * 1. Always try network first
 * 2. For navigation requests that fail:
 *    - If critical route (/add-listing, /dashboard, etc), return cached app shell
 *    - If navigator.onLine is false, return offline.html
 *    - Otherwise return cached page or app shell
 * 3. For API requests, never return offline.html - return error or let it fail
 * 4. Admin routes bypass service worker entirely
 */
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);
  
  // Admin routes bypass service worker entirely (always fresh from network)
  if (url.pathname === '/admin' || url.pathname.startsWith('/admin/')) {
    event.respondWith(fetch(event.request));
    return;
  }

  // For navigation requests, implement smart fallback
  if (isNavigationRequest(event.request)) {
    event.respondWith(
      fetch(event.request)
        .then(response => {
          // Network request succeeded - return it
          return response;
        })
        .catch(async (error) => {
          console.log('[SW] Navigation request failed:', url.pathname, error.message);
          
          // Check if user is truly offline
          const isOffline = !self.navigator.onLine;
          
          // Critical routes should NEVER show offline page - return cached shell
          if (isCriticalRoute(url.pathname)) {
            console.log('[SW] Critical route failed, returning cached shell instead of offline page');
            
            // Try to get cached app shell (index.html)
            const cache = await caches.open('workbox-precache-v2-' + self.location.origin);
            const cachedShell = await cache.match('/index.html') || 
                                await cache.match('/');
            
            if (cachedShell) {
              return cachedShell;
            }
            
            // If no cached shell, return a minimal error response
            // The app will show the connection banner
            return new Response(
              '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="3"></head><body>Loading...</body></html>',
              { 
                headers: { 'Content-Type': 'text/html' },
                status: 200 
              }
            );
          }
          
          // For other navigation requests:
          // - If truly offline (navigator.onLine === false), show offline page
          // - Otherwise, return cached page or shell (network might be unstable)
          if (isOffline) {
            console.log('[SW] User is offline, returning offline page');
            const cache = await caches.open('workbox-precache-v2-' + self.location.origin);
            const offlinePage = await cache.match('/offline.html');
            
            if (offlinePage) {
              return offlinePage;
            }
          }
          
          // Network is unstable but user is technically online
          // Try to return cached version of the page or app shell
          console.log('[SW] Network unstable, trying cached page or shell');
          const cache = await caches.open('workbox-precache-v2-' + self.location.origin);
          
          // Try cached version of the exact page
          const cachedPage = await cache.match(event.request);
          if (cachedPage) {
            return cachedPage;
          }
          
          // Fall back to app shell
          const cachedShell = await cache.match('/index.html') || 
                              await cache.match('/');
          if (cachedShell) {
            return cachedShell;
          }
          
          // Last resort: show offline page
          const offlinePage = await cache.match('/offline.html');
          if (offlinePage) {
            return offlinePage;
          }
          
          // No cache available at all - return basic error
          return new Response('Network error', { status: 503 });
        })
    );
    return;
  }
  
  // For API requests, NEVER return offline.html
  // Let the request fail naturally so the app can handle it
  if (isApiRequest(url)) {
    event.respondWith(
      fetch(event.request)
        .catch(error => {
          console.log('[SW] API request failed, returning error:', url.pathname);
          // Return a proper error response that the app can handle
          return new Response(
            JSON.stringify({ 
              error: 'Network error', 
              message: 'Unable to reach the server. Please check your connection.' 
            }),
            { 
              status: 503,
              headers: { 'Content-Type': 'application/json' }
            }
          );
        })
    );
    return;
  }
  
  // For all other requests (assets, fonts, etc.), let Workbox handle them
  // The registerRoute calls below will handle these
});

// Runtime caching strategies (same as vite.config.ts)
// Cache images (CacheFirst)
registerRoute(
  ({ url }) => url.pathname.match(/\.(?:png|jpg|jpeg|svg|gif|webp|avif)$/i),
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase Storage images (CacheFirst)
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/storage/v1/object/public/'),
  new CacheFirst({
    cacheName: 'supabase-images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Supabase API calls (NetworkFirst) - EXCLUDE auth endpoints
registerRoute(
  ({ url, request }) => {
    // Only cache GET requests
    if (request.method !== 'GET') return false;
    
    // Don't cache auth endpoints
    if (url.pathname.includes('/auth/')) return false;
    
    // Don't cache if has auth header
    const hasAuthHeader = request.headers.has('Authorization') || 
                         request.headers.has('apikey');
    if (hasAuthHeader) return false;
    
    // Cache Supabase REST API calls
    return url.hostname.includes('supabase.co') && 
           url.pathname.includes('/rest/');
  },
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Google Fonts (CacheFirst)
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || 
               url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// ============================================================================
// PUSH NOTIFICATION HANDLERS
// ============================================================================

/**
 * Handle push notification received event
 * Display a notification to the user
 */
self.addEventListener('push', (event: PushEvent) => {
  console.log('[Service Worker] Push notification received:', event);

  if (!event.data) {
    console.log('[Service Worker] Push event has no data');
    return;
  }

  try {
    const data = event.data.json();
    const title = data.title || 'TopAffaireImmo';
    const options: NotificationOptions = {
      body: data.body || '',
      icon: data.icon || '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      tag: data.tag || 'default',
      requireInteraction: data.requireInteraction || false,
      data: data.data || {},
      // Action buttons (optional) - Typed as any to avoid NotificationOptions type issues
    } as NotificationOptions & { actions?: Array<{ action: string; title: string }> };

    // Add actions if provided
    if (data.actions) {
      (options as any).actions = data.actions;
    }

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (error) {
    console.error('[Service Worker] Error handling push event:', error);
    
    // Fallback: show basic notification
    event.waitUntil(
      self.registration.showNotification('TopAffaireImmo', {
        body: 'Vous avez une nouvelle notification',
        icon: '/icons/icon-192.png',
      })
    );
  }
});

/**
 * Handle notification click event
 * Open the app or navigate to specific URL
 */
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[Service Worker] Notification clicked:', event);

  event.notification.close();

  // Get the URL to open from notification data
  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    // Check if there's already a window open
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if (client.url === new URL(urlToOpen, self.location.origin).href && 'focus' in client) {
          return client.focus();
        }
      }
      
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

/**
 * Handle push subscription change
 * This is called when a push subscription expires or is replaced
 */
self.addEventListener('pushsubscriptionchange', (event: Event) => {
  console.log('[Service Worker] Push subscription changed:', event);
  
  // You can implement automatic re-subscription here if needed
  // For now, we'll just log it
});

// Skip waiting and claim clients immediately
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

console.log('[Service Worker] Loaded with push notification support');
