-- =====================================================
-- Migration 024: Sample Properties (DEPRECATED)
-- =====================================================
-- This migration previously contained demo/seed data.
-- All demo data has been moved to: supabase/seed/seed_demo_data.sql
-- 
-- This file is kept empty to maintain migration numbering.
-- This is a no-op migration and is safe to apply.
-- =====================================================