-- =====================================================
-- Migration 024_sample_properties_data: (DEPRECATED)
-- =====================================================
-- This migration previously contained demo/seed data.
-- All demo data has been moved to: supabase/seed/seed_demo_data.sql
-- 
-- This file is kept empty to maintain migration numbering.
-- =====================================================
